app/missions/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, Response, flash
from sqlalchemy import desc, or_
from app import db
from werkzeug import secure_filename

from .models import Mission
from app.database.database import CmpMission, CmpComment

from config import SERVER_MISSION_FOLDER, TEMPORARY_MISSION_FOLDER

import datetime
import os
import re


mod_missions = Blueprint('missions', __name__, url_prefix='/missions',
                       template_folder='templates')

@mod_missions.route('/')
def display_missions():
    populate_database()
    return render_template('index.html', data=missions_in_database())


def populate_database():
    folder_missions = []
    database_missions = db.session.query(CmpMission).all()

    # build database from hardrive.
    for file in os.listdir(SERVER_MISSION_FOLDER):
        if file.endswith(".pbo"):

            temp_name = re.sub('(?:[.](.*)|_[vV]([0-9]+(.*))?)', '', file)
            world_name = file.split('.')[1]
            created = datetime.datetime.now()
            created.strftime("%Y-%m/%d %H:%M")

            # fetch the author from file
            with open(SERVER_MISSION_FOLDER+file, 'r', encoding="utf8", errors='ignore') as missionfile:
                mission_contents = missionfile.readlines()


            for line in mission_contents:
                line = line.strip()

                if "author" in line:
                    author = re.findall(r'"([^"]*)"', line)


            temp_mission = CmpMission(temp_name, world_name, author[0], file, "Accepted", "", 0, created, SERVER_MISSION_FOLDER)
            folder_missions.append(temp_mission)

            # this test needs to be first, wtf
            if temp_mission not in database_missions:
                db.session.add(temp_mission)


    db.session.commit()


def missions_in_database():
    return db.session.query(CmpMission).filter(or_(CmpMission.status == "Accepted", CmpMission.status == "Unknown"))


@mod_missions.route('/submissions/')
def display_submissions():
    missions = db.session.query(CmpMission).filter(or_(CmpMission.status != "Accepted")).all()
    missions.sort(key=lambda x: x.created, reverse=False)
    return render_template('modqueue.html', data=missions, today=datetime.date.today())


@mod_missions.route('/submissions/submit/', methods=['POST', 'GET'])
def submit_mission():
    error = None

    if request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):

            filename = secure_filename(file.filename)

            min_play = request.form['min_play']

            if valid_mission(file, min_play):

                file.save(TEMPORARY_MISSION_FOLDER + file.filename) #Save to temp folder
                staff_notes = request.form['freetext']

                # remove versoning numbers
                temp_name = re.sub('(?:[.](.*)|_[vV]([0-9]+(.*))?)', '', file.filename)
                world_name = file.filename.split('.')[1]
                created = datetime.datetime.now()
                created.strftime("%Y-%m/%d %H:%M")
                temp_mission = CmpMission(temp_name, world_name, "soju", file.filename, "Evaluating", staff_notes, min_play, created, TEMPORARY_MISSION_FOLDER)

                # Send it to the db
                db.session.add(temp_mission)
                db.session.commit()
                obj = db.session.query(CmpMission).order_by('-id').first()
                flash("Your mission has been sucsessfully been submitted.")
                # Email routine should kick in here
                return redirect(url_for('missions.view_submission', id=obj.id))

        else:
            flash("Please only submit pbo files.")

    return render_template('submit.html', error=error)


@mod_missions.route('/<name>')
def view_mission_on_server(name):
    selected_mission=db.session.query(CmpMission).filter(CmpMission.name == name).first()
    if (selected_mission != None):
        return render_template('mission.html', data=selected_mission)

    else:
        return redirect(url_for('missions.display_missions'))


@mod_missions.route('/submissions/view/<id>', methods=['POST', 'GET'])
def view_submission(id):
    # if no submissions are found, display the
    # normal mission overiew
    selected_mission=db.session.query(CmpMission).filter(CmpMission.id == id and CmpMission.status != "Accepted").first()
    if selected_mission is not None and selected_mission.status != "Accepted":

        mission_comments = db.session.query(CmpComment).filter(CmpComment.mission_id == id).all()




        if request.method == 'POST':
            if (request.form['submit'] == 'Delete'):
                value = delete_mission(selected_mission)

                if (value == -1):
                    print("Failed to delete mission")
                    return "Error, failed to delete mission"

                return redirect(url_for('missions.display_submissions'))


            if 'Comment' in request.form.values():
                commenText = request.form['comment']
                created = datetime.datetime.now()
                created.strftime("%Y-%m/%d %H:%M")
                temp_obj = CmpComment(id, commenText, created, "soju")
                db.session.add(temp_obj)
                db.session.commit()
                flash("Your comment has been submitted")

            else:
                selected_mission.status = request.form['status']
                selected_mission.host_notes = request.form['host_notes']
                selected_mission.min_play = request.form['min_play']
                selected_mission.update = datetime.datetime.now();
                if selected_mission.status == "Accepted":

                    # Since the mission was accepted, move it to the server folder
                    try:
                        os.rename(TEMPORARY_MISSION_FOLDER +  selected_mission.raw_name,
                            SERVER_MISSION_FOLDER +  selected_mission.raw_name)
                    except FileNotFoundError:
                        return "Fatal error, the file is not in the temporary folder, blame Hidden and keep calm" # error must be expanded

                    selected_mission.folder = SERVER_MISSION_FOLDER
                    flash("Mission is now flagged as accepted, it has been moved to the server.")

                flash("Mission successfully updated")
                db.session.commit()


        status = ["Unknown", "Evaluating", "Broken/legacy", "Accepted", "Rejected"]

        # A tad ugly, but we need the item to be garantueed first in the list.
        status.remove(selected_mission.status)
        status.insert(0, selected_mission.status)
        mission_comments.sort(key=lambda x: x.created, reverse=True)
        return render_template('view_submission.html', mission = selected_mission, statuses=status, comments=mission_comments, folder=TEMPORARY_MISSION_FOLDER)

    return redirect(url_for('missions.display_submissions'))


def allowed_file(filename):
    # Must log attempts at malicious files and notify staff
    ALLOWED_EXTENSIONS = set(['pbo'])
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


def delete_mission(mission):
    # deletes file from database
    # and local file
    selected_mission=db.session.query(CmpMission).filter(CmpMission.name == mission.name).first()
    if (selected_mission == None):
        flash("Failed to delete the mission")
        return -1
    try:
        os.remove(mission.folder + mission.raw_name)
    except FileNotFoundError:
        print("Failed to delete file, it could not be found")

    db.session.delete(selected_mission)
    db.session.commit()
    return 1



def valid_mission(file, min_play):
    #check file name
    mission_name_split = file.filename.split("_")

    if len(mission_name_split) >= 2:

        provided_playable = mission_name_split[1]
        try:
            provided_playable = int(re.sub('[^0-9]','', provided_playable))
        except ValueError:
            flash("Your mission name appears to not follow the naming convention.")
            return False

        raw_text = file.read()
        file.seek(0)
        mission_contents = str(raw_text)


        actual_playable = []
        actual_playable.append(int(mission_contents.count("isPlayable=1;")))
        actual_playable.append(int(mission_contents.count('player="PLAYER COMMANDER";')))
        actual_playable.append(int(mission_contents.count("isPlayable") - int(mission_contents.count("HeadlessClient_F"))))
        actual_playable.append(int(mission_contents.count("isPlayer")))

        if not (provided_playable in actual_playable):
            flash("Your mission has " + str(actual_playable[2]) + " " + str(actual_playable[3]) + " While file name is " + str(provided_playable))
            return False

        if not re.search('ark+_[a-z]+[0-9]+_.+[.].+[.]pbo', file.filename):
            flash("Your mission name appears to not follow the naming convention.")
            return False

        if int(min_play) > provided_playable:
            flash("Minimum amounts of players are higher than actual playable units")
            return False


        return True
    else:
        return False

app/missions/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Arma 3 missions</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <script src="{{ url_for('static', filename='js/missions.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
</head>
<body>
    <div class="header">
        <div class="header-text">
            Missionary
        </div>
            <ul class=navbar>
              <li><a href="{{url_for('missions.display_submissions')}}">Submissions</a></li>
              <li><a class="navbar-active"  href="{{url_for('missions.display_missions')}}">On server</a></li>
              <li><a href="{{url_for('missions.submit_mission')}}">Submit</a></li>
            </ul>
    </div>
    <div class="content">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Mission name</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>World</th>
                    <th>Author</th>
                </tr>
            </thead>
            <tbody>
            {% for mission in data %}
                <tr>
                    <th scope="row">{{loop.index}}</th>
                    <td><a href="{{url_for('missions.view_mission_on_server', name = mission.name)}}">{{mission.name}}</a></td>
                    <td><span class="label label-{{mission.status}}">{{mission.status}}</span></td>
                    <td><span class="value mission-type {{mission.mission_type}}">{{mission.mission_type}}</span></td>
                    <td>{{mission.world}}</td>
                    <td>{{mission.author}}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

app/missions/templates/modqueue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Missions in database</title>
    <script src="{{ url_for('static', filename='js/missions.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
</head>
<body>
    <div class="header">
        <div class="header-text">
            Missionary
        </div>
        <ul class=navbar>
          <li><a class="navbar-active" href="{{url_for('missions.display_submissions')}}">Submissions</a></li>
          <li><a href="{{url_for('missions.display_missions')}}">On server</a></li>
          <li><a href="{{url_for('missions.submit_mission')}}">Submit</a></li>
        </ul>
    </div>
    <div class="content">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Mission name</th>
                    <th>Status</th>
                    <th>Updated</th>
                    <th>Submitted</th>
                    <th>Type</th>
                    <th>World</th>
                    <th>Author</th>
                </tr>
            </thead>
            <tbody>
            {% for mission in data %}
                <tr>
                    <th scope="row">{{loop.index}}</th>
                    <td><a href="{{url_for('missions.view_submission', id = mission.id)}}">{{mission.name}}</a></td>
                    <td><span class="label label-{{mission.status}}">{{mission.status}}</span></td>
                    <td>{{mission.update}}</td>
                    <td>
                        <span title="{{mission.created}}">{{ 'today' if (today - mission.created.date()).days <= 0 else (today - mission.created.date()).days ~ ' days ago' }}</span>
                    </td>
                    <td><span class="value mission-type {{mission.mission_type}}">{{mission.mission_type}}</span></td>
                    <td>{{mission.world}}</td>
                    <td>{{mission.author}}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</body>
</html>

app/missions/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Missionary - Submit a mission</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
</head>
<body>
    <div class="header">
        <div class="header-text">
            Missionary
        </div>
        <ul class=navbar>
            <li><a href="{{url_for('missions.display_submissions')}}">Submissions</a></li>
            <li><a href="{{url_for('missions.display_missions')}}">On server</a></li>
            <li><a class="navbar-active" href="{{url_for('missions.submit_mission')}}">Submit</a></li>
        </ul>
    </div>
    <div class="content">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}
        <form action="{{url_for('missions.submit_mission')}}" method=post enctype=multipart/form-data>
            <table class="table table-bordered table-hover sortable table-condensed">
                <tr>
                </tr>
                <tr>
                    <td>Minimun amounts of players</td>
                    <td><input type="text" name="min_play" onkeypress='return event.charCode >= 48 && event.charCode <= 57'></input></td>
                </tr>
                <tr>
                    <td>Notes to hosts</td>
                    <td><textarea cols="50" rows="8" name="freetext"></textarea></td>
                </tr>
                <tr>
                    <td>
                    <input type="file" name="file" id="file" class="inputfile inputfile-1" data-multiple-caption="{count} files selected" multiple />
                    <label for="file"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg></path><span>Choose a file&hellip;</span></label></td>
                    <td><input type=submit value=Upload></td>

                </tr>
            </table>
        </form>
    </div>
    <div class="col-3"></div>
</body>
</html>